server:
  port: 9008
spring:
  application:
    name: hrm-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm_user
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:com/ymy/hrm/mapper/*Mapper.xml
  type-aliases-package: com.ymy.hrm.domain,com.ymy.hrm.query
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true